### PR TITLE
New "Order IT Hardware demo" for Process Automation Manager 7

### PR DESCRIPTION
**Pull request by DuncanDoyle**

### CODE REVIEW

**Comment by fridim** [comment]
can you make the CI tests pass ? Error is:

```
Ansible Deprecation Checks
Error: The `include` directive is deprecated in Ansible 2.4.
https://github.com/ansible/ansible/blob/devel/CHANGELOG.md
  File: /home/travis/build/sborenst/ansible_agnostic_deployer/ansible/roles/ocp-workload-pam-order-it-hardware/tasks/main.yml
  Found: "include: ./pre_workload.yml"
  Found: "include: ./workload.yml"
  Found: "include: ./post_workload.yml"
  Found: "include: ./remove_workload.yml"
```

Use `import_tasks` instead of ~`include`~.

**Comment by fridim** [comment]
Also:

```
ansible/roles/ocp-workload-pam-order-it-hardware/files/rhpam70-businesscentral-openshift-with-users.yaml:
  1:1       warning  missing document start "---"  (document-start)
ansible/roles/ocp-workload-pam-order-it-hardware/tasks/workload.yml:
  86:1      error    too many blank lines (3 > 2)  (empty-lines)
  148:1     error    too many blank lines (3 > 2)  (empty-lines)
```

**Comment by fridim** [comment]
@DuncanDoyle any chance to fix the syntax warnings & deprecation errors ?

Is this ready to merge ?

**Comment by DuncanDoyle** [comment]
@fridim Will take a look today or tomorrow. Sorry for late reply.

**Comment by DuncanDoyle** [comment]
@fridim I'm still working on some additional improvements after some reviews. Can you wait with merging until those changes are in? Will notify you when I'm done.

**Pull request merged**
