### PR TITLE
Overhaul of the ssh config file generation

### PR DESCRIPTION
**Pull request by thoraxe**
* Stops including the bastion as a host that should be proxied (causes a
loop)

* adds a config directive to the proxycommand (to properly pick up the
bastion host config)

I'm testing this right now on our provisioning host. I copied the /opt/ansible_agnostic_deployer folder to /opt/dev_dep and checked out this branch. It's not having SSH issues and it is up to the installation of openshift node packages.

I'll wait for the complete installation to finish, but it's looking promising right now.

### CODE REVIEW

**Comment by thoraxe** [comment]
```
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=13   changed=3    unreachable=0    failed=0   
ec2-34-204-76-51.compute-1.amazonaws.com : ok=13   changed=11   unreachable=0    failed=0   
ec2-34-224-6-156.compute-1.amazonaws.com : ok=59   changed=51   unreachable=0    failed=0   
ec2-52-3-220-15.compute-1.amazonaws.com : ok=13   changed=11   unreachable=0    failed=0   
ec2-54-197-122-175.compute-1.amazonaws.com : ok=16   changed=13   unreachable=0    failed=0   
ec2-54-210-247-172.compute-1.amazonaws.com : ok=14   changed=11   unreachable=0    failed=0   
ec2-54-242-206-165.compute-1.amazonaws.com : ok=26   changed=24   unreachable=0    failed=0   
```

run on your host.

**Comment by thoraxe** [comment]
Rebased on 2017-MAY-30

**Comment by sborenst** [comment]
There is an issue here for non-openshift deployments: 
+      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '**_master**') | replace('-', '_')] }}"
 +      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '**_node**') | replace('-', '_')] }}"
 +      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '**_support**') | replace('-', '_')] }}"
 +      - "{{ groups[('tag_' ~ env_type ~ '_' ~ guid ~ '**_infranode**') | replace('-', '_')] }}"

**Comment by thoraxe** [comment]
True, sort of. The difficulty is that you need a group of hosts that specifically excludes the bastion. Otherwise you proxy the connection to the proxy which causes an infinite loop. 

I can go back and create a "proxied" group in my CF template, but you'll still need to do that, too. 

By the way, without these changes I am somewhat confident that none of your environments are actually using proxied connections. Ansible does SSH by ip but reports the hostnames back when printing them to stdout during a run. Since you are including the proxy in the list of proxied hosts, if it was working it would be infinite looping.

**Comment by sborenst** [comment]
@thoraxe I'm happy to merge this as soon as we can get this to be less OpenShift specific, having a "proxied" tag is not a bad idea.

**Comment by thoraxe** [comment]
I'm not sure I understand. Switching to "proxied" tag/group makes it non-OpenShift specific.

Where are there still OpenShift-specific parts? I'm happy to work to remove them.

**Comment by sborenst** [comment]
Added to backlog, we will fix this using the new process

**Pull request closed without merging**
